---
version: "3"

tasks:
  push:
    desc: Push changes to github io and blog repo
    cmds:
      - hugo
      # - task: push-github-io
      - task: push-blog
  push-github-io:
    desc: Deploy updates to github io repo
    dir: public
    cmds:
      - git add .
      - msg="rebuilding site $(date)" && git commit -m "$msg"
      - git push origin master
  push-blog:
    desc: Push new changes to blog repo
    cmds:
      - git add .
      - git commit -m "{{.COMMIT_MSG}}"
      - git push origin master
  pull:
    desc: Pull changes from submodule repo and blog repo
    cmds:
      - git pull
      - git submodule update --init --recursive
